# Generated by Django 5.0.6 on 2024-06-12 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uni", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="carrera",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="uni.carrera",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="profesor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="uni.profesor",
            ),
        ),
    ]
