# Generated by Django 5.0.6 on 2024-06-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uni", "0002_curso_carrera_curso_profesor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="dni",
            field=models.IntegerField(unique=True),
        ),
    ]
