# Generated by Django 5.0.6 on 2024-06-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uni", "0003_alter_alumno_dni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrera",
            name="nombre",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="dni",
            field=models.IntegerField(unique=True),
        ),
    ]
