# Generated by Django 5.0.6 on 2024-06-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uni", "0004_alter_carrera_nombre_alter_profesor_dni"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="ciclo",
            field=models.CharField(
                choices=[
                    ("I", "Primer Ciclo"),
                    ("II", "Segundo Ciclo"),
                    ("III", "Tercer Ciclo"),
                    ("IV", "Cuarto Ciclo"),
                    ("V", "Quinto Ciclo"),
                    ("VI", "Sexto Ciclo"),
                ],
                default="I",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="ciclo",
            field=models.CharField(
                choices=[
                    ("I", "Primer Ciclo"),
                    ("II", "Segundo Ciclo"),
                    ("III", "Tercer Ciclo"),
                    ("IV", "Cuarto Ciclo"),
                    ("V", "Quinto Ciclo"),
                    ("VI", "Sexto Ciclo"),
                ],
                default="I",
                max_length=3,
            ),
        ),
    ]
